### ISSUE TITLE
Tìm hiểu đề tài

### ISSUE THREAD

**Issue by leduanSt1** [leduanSt1/CCVMTPTPM_NHOM6#1]
Tìm hiểu đề tài "Phát triển Dashboard hiện thông tin từ API"

- [x] Tìm hiểu về yêu cầu của đề tài
- [x] Các chức năng cần có đề tài
- [x]  Yêu cầu của chức năng

**Comment by ngocduy1902** [comment]
## Để phát triển đề tài dashboard hiển thị thông tin từ API có một vài yêu cầu cần chú ý
- Yêu cầu về chức năng: Có các chức năng cơ bản của một dashboard như hiển thị số liệu, thống kê, bảng biểu, hỗ trợ tìm kiếm, lọc thông tin.
- Yêu cầu về giao diện: Các yêu cầu này có thể bao gồm màu sắc, bố cục, kiểu font chữ, kích thước các thành phần trên dashboard...
- Yêu cầu về dữ liệu: Biết cách lấy và xử lý dữ liệu từ API để dashboard hoạt động đúng cách
- Ngoài ra còn một số yêu cầu khác như yêu cầu về bảo mật, hiệu suất và tích hợp...

**Comment by ngocduy1902** [comment]
## Các chức năng cơ bản mà đề tài dashboard hiển thị thông tin từ API cung cấp bao gồm:
- Hiển thị dữ liệu từ API: Dữ liệu này có thể là thông tin số liệu thống kê, biểu đồ, bảng thông tin, hình ảnh, video hoặc bất kỳ loại dữ liệu nào khác từ API.
- Lọc dữ liệu: Cho phép người dùng xem dữ liệu tùy theo nhu cầu.
- Tìm kiếm: Giúp người dùng tìm kiếm dữ liệu nhanh chóng, có thể tích hợp với chức năng lọc dữ liệu.
- Hiển thị thông tin dưới dạng biểu đồ, bảng.
## Có thể bổ sung thêm

**Comment by ngocduy1902** [comment]
## Các chức năng cơ bản mà đề tài dashboard hiển thị thông tin từ API cung cấp bao gồm (bổ sung):
- Tính năng xuất dữ liệu: file csv, excel hoặc pdf.
- Tính năng bảo mật và phân quyền: người dùng phải truy cập vào dashboard mới được phép truy cập thông tin từ API

**Comment by ngocduy1902** [comment]
## Các yêu cầu đổi với mỗi chức năng của đề tài
- Chức năng hiển thị dữ liệu: Địa chỉ URL của API endpoint cần được xác định để có thể truy xuất dữ liệu. Nếu API yêu cầu xác thực, thì dashboard cần có khả năng xử lý xác thực này để truy cập vào API. Dữ liệu từ API có thể được trả về dưới dạng JSON hoặc XML, dashboard có khả năng xử lý và chuyển đổi những dữ liệu này thành các thông tin hiển thị trên dashboard.
- Tìm kiếm và lọc dữ liệu: Dashboard có khả năng lọc dữ liệu theo các tiêu chí cụ thể, hoặc tìm kiếm thông tin cụ thể từ dữ liệu.
- Biểu đồ, bảng: Thống kê dữ liệu dưới các dạng biểu đồ khác nhau.
- Xuất dữ liệu: Có thể xuất dữ liệu thành các file như csv, excel, pdf để người dùng tiến hành phân tích dữ liệu.
