### ISSUE TITLE
Tìm hiểu về Testing tool và demo

### ISSUE THREAD

**Issue by ngocduy1902** [leduanSt1/CCVMTPTPM_NHOM6#4]
## Các task cần thực hiện:
- [x] Lý thuyết chung về testing tool
- [x] Xác định các loại test có trong đề tài
- [x] Xác định các công cụ test cụ thể cho mỗi loại test
- [x] Phân tích các công cụ test sử dụng trong đề tài
- [x] Cài đặt một vài công cụ test
- [x] Demo test một giao diện
- [x] Demo test API login

**Comment by ngocduy1902** [comment]
Hoàn thành task 1 - Lý thuyết chung về testing tool 
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)
[](url)

**Comment by ngocduy1902** [comment]
Hoàn thành task 2 - Xác định các loại công cụ test cho đề tài
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)

**Comment by ngocduy1902** [comment]
Hoàn thành task 3 - Xác định các công cụ test cụ thể cho mỗi loại test
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)

**Comment by ngocduy1902** [comment]
Hoàn thành task 4 -  Phân tích các công cụ test sử dụng trong đề tài
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)

**Comment by duynn01092002** [comment]
Hoàn thành task 5 - Cài đặt một vài công cụ test
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)

**Comment by ngocduy1902** [comment]
Hoàn thành task 6 - Demo test giao diện
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)

**Comment by ngocduy1902** [comment]
Hoàn thành task 7 - Demo test một chức năng
[Sprint 2 - Week8](https://docs.google.com/document/d/1xRKnmZpVQK4qAjr1G8yDMzSPSBL271kQahYY44_7enI/edit?usp=sharing)
